syntax = "proto3";

option csharp_namespace = "FSR.DigitalTwin.App.GRPC.Process.HRC";

package FSR.DigitalTwin.App.GRPC;

message FunctionPropertyDataDTO {
    string functionId = 1;
    string procedureName = 2;
    string procedureDescr = 3;
    string procedureId = 4;
    double duration = 5;
    double durationUncertainty = 6;
}

message FunctionObjectDataDTO {
    string functionId = 1;
    string target = 2;
    string startLocation = 3;
    string endLocation = 4;
    string location = 5; 
}

enum Agent {
    AGENT_ANY = 0;
    AGENT_HUMAN = 1;
    AGENT_ROBOT = 2;
}

message HRCTaskDTO {
    string id = 1;
    string type = 2;
    string target = 3;
    string name = 4;
    string description = 5;
    string goal = 6;
    Agent agent = 7;
    int64 minDuration = 8;
    int64 maxDuration = 9;
    int64 duration = 10;
    int64 durationUncertainty = 11;
    double successRate = 12;
}

message HRCModelDTO {
    int64 horizon = 1;
    repeated HRCTaskDTO tasks = 2;
    repeated HRCTaskDTO robotTasks = 3;
    repeated HRCTaskDTO humanTasks = 4;
}

message GoalDTO {
    string goalId = 1;
}

message TaskConstituentListDTO {
    repeated string constituents = 1; 
}

message TaskDecompositionDTO {
    string goalId = 1;
    map<string, TaskConstituentListDTO> graph = 2;
}