// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Services/HRCProcessSimulationService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService {
  public static partial class HRCProcessSimulationService
  {
    static readonly string __ServiceName = "FSR.DigitalTwin.App.GRPC.HRCProcessSimulationService";

    static readonly grpc::Marshaller<global::FSR.DigitalTwin.App.GRPC.Empty> __Marshaller_FSR_DigitalTwin_App_GRPC_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.DigitalTwin.App.GRPC.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO> __Marshaller_FSR_DigitalTwin_App_GRPC_HRCModelDTO = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO> __Marshaller_FSR_DigitalTwin_App_GRPC_GoalDTO = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO> __Marshaller_FSR_DigitalTwin_App_GRPC_TaskDecompositionDTO = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO.Parser.ParseFrom);

    static readonly grpc::Method<global::FSR.DigitalTwin.App.GRPC.Empty, global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO> __Method_CreateHRCModel = new grpc::Method<global::FSR.DigitalTwin.App.GRPC.Empty, global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateHRCModel",
        __Marshaller_FSR_DigitalTwin_App_GRPC_Empty,
        __Marshaller_FSR_DigitalTwin_App_GRPC_HRCModelDTO);

    static readonly grpc::Method<global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO, global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO> __Method_DecomposeHRCTask = new grpc::Method<global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO, global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DecomposeHRCTask",
        __Marshaller_FSR_DigitalTwin_App_GRPC_GoalDTO,
        __Marshaller_FSR_DigitalTwin_App_GRPC_TaskDecompositionDTO);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::FSR.DigitalTwin.App.GRPC.Process.HRC.Services.HRCProcessSimulationService.HRCProcessSimulationServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HRCProcessSimulationService</summary>
    [grpc::BindServiceMethod(typeof(HRCProcessSimulationService), "BindService")]
    public abstract partial class HRCProcessSimulationServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO> CreateHRCModel(global::FSR.DigitalTwin.App.GRPC.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO> DecomposeHRCTask(global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HRCProcessSimulationService</summary>
    public partial class HRCProcessSimulationServiceClient : grpc::ClientBase<HRCProcessSimulationServiceClient>
    {
      /// <summary>Creates a new client for HRCProcessSimulationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HRCProcessSimulationServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HRCProcessSimulationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HRCProcessSimulationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HRCProcessSimulationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HRCProcessSimulationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO CreateHRCModel(global::FSR.DigitalTwin.App.GRPC.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateHRCModel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO CreateHRCModel(global::FSR.DigitalTwin.App.GRPC.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateHRCModel, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO> CreateHRCModelAsync(global::FSR.DigitalTwin.App.GRPC.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateHRCModelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO> CreateHRCModelAsync(global::FSR.DigitalTwin.App.GRPC.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateHRCModel, null, options, request);
      }
      public virtual global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO DecomposeHRCTask(global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DecomposeHRCTask(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO DecomposeHRCTask(global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DecomposeHRCTask, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO> DecomposeHRCTaskAsync(global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DecomposeHRCTaskAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO> DecomposeHRCTaskAsync(global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DecomposeHRCTask, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HRCProcessSimulationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HRCProcessSimulationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HRCProcessSimulationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateHRCModel, serviceImpl.CreateHRCModel)
          .AddMethod(__Method_DecomposeHRCTask, serviceImpl.DecomposeHRCTask).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HRCProcessSimulationServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateHRCModel, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::FSR.DigitalTwin.App.GRPC.Empty, global::FSR.DigitalTwin.App.GRPC.Process.HRC.HRCModelDTO>(serviceImpl.CreateHRCModel));
      serviceBinder.AddMethod(__Method_DecomposeHRCTask, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::FSR.DigitalTwin.App.GRPC.Process.HRC.GoalDTO, global::FSR.DigitalTwin.App.GRPC.Process.HRC.TaskDecompositionDTO>(serviceImpl.DecomposeHRCTask));
    }

  }
}
#endregion
